# Проводит проверки линтера

name: Run all repo checks

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint-strict-dev-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v6
    - name: Setup uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Lint with ruff base task rules
      run: |
        # Run the strictest ruff checks possible to satisfy EVERYTHING
        uv run ruff check --select ALL .

  # Run all complience checks
  compliance-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v6
    - name: Setup uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Lint with ruff base task rules
      run: |
        # Stop the build if there are Python syntax errors
        uv run ruff check .
    - name: Test repo on uv runing
      run: |
        # We run this check because this program runs non-blocking and must return immediate result
        uv run catalog_analysis.py
